# Use nginx to serve static files
FROM nginx:alpine

COPY default.conf /etc/nginx/conf.d/default.conf

# Copy all frontend files to nginx default folder
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80
